/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-10-16 09:16:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div class=\"row content\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<h2 id=\"region-name\">선택지역</h2>\r\n");
      out.write("\t\t\t\t<div id=\"korea\" style=\"width: 600px; height: 800px;\"></div>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"js/raphael-min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"js/korea.js\"></script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-1\">\r\n");
      out.write("\t\t\t\t<div id=\"sido-data\" style=\"margin: 0 auto;\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("<!-- \t\t\t\t<div id=\"popup-background\" onclick=\"fade_map()\"></div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t \r\n");
      out.write("  <div class=\"modal fade\" id=\"mypar\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      Modal content\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\" style=\"padding:35px 50px;\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4><span class=\"glyphicon glyphicon-lock\"></span> 약국 리스트</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\" style=\"padding:40px 50px;\">\r\n");
      out.write("          <div id=\"public-data\" style=\"margin: 0 auto;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("        \t<div id=\"popup\"></div>\r\n");
      out.write("        \t<div id=\"googleMap\" style=\"height:400px;width:100%;\" onclick=\"fade_map()\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"popup-background\" onclick=\"fade_map()\"></div>\r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-danger btn-default pull-left\" data-dismiss=\"modal\"><span class=\"glyphicon glyphicon-remove\"></span> Cancel</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction show_map(latitude, longitude, pharmacy_name) {\r\n");
      out.write("// \t\t$('#popup').css('display', 'block');\r\n");
      out.write("// \t\t$('#popup-background').css('display', 'block');\r\n");
      out.write("\r\n");
      out.write("\t\t//     var myLatLng = {lat: -25.363, lng: 131.044};\r\n");
      out.write("\t\tvar myLatLng = new google.maps.LatLng(latitude, longitude);\r\n");
      out.write("\r\n");
      out.write("\t\t// Create a map object and specify the DOM element\r\n");
      out.write("\t\t// for display.\r\n");
      out.write("\t\tvar map = new google.maps.Map(document.getElementById('googleMap'), {\r\n");
      out.write("\t\t\tcenter : myLatLng,\r\n");
      out.write("\t\t\tzoom : 15,\r\n");
      out.write("\t\t\tmapTypeId : google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// Create a marker and set its position.\r\n");
      out.write("\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\tmap : map,\r\n");
      out.write("\t\t\tposition : myLatLng,\r\n");
      out.write("\t\t\ttitle : pharmacy_name\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tmarker.serMap(map);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction fade_map() {\r\n");
      out.write("\t\t$('#popup').css('display', 'none');\r\n");
      out.write("\t\t$('#popup-background').css('display', 'none');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction go_search(gun){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: 'data/pharmacy',\r\n");
      out.write("\t\t\tdata : { gungu:gun},\r\n");
      out.write("\t\t\tsuccess: function( data ){\r\n");
      out.write("\t\t\t\tvar tag = \"<table>\";//\r\n");
      out.write("\t\t\t\t$(data).find('item').each(function(idx){\r\n");
      out.write("\t\t\t\t\tvar map_data = $(this).find('wgs84Lat').text()+','\r\n");
      out.write("\t\t\t\t\t\t\t\t+  $(this).find('wgs84Lon').text()+',\"'\r\n");
      out.write("\t\t\t\t\t\t\t\t+  $(this).find('dutyName').text()+'\"';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\ttag += \"<tr><td>\"+ (idx+1) +\"</td>\"\r\n");
      out.write("\t\t\t\t\t\t+  \"<td><a onclick='show_map(\"+ map_data+ \")'>\"+$(this).find('dutyName').text() + \"</a></td>\"\r\n");
      out.write("\t\t\t\t\t\t+  \"<td>\"+$(this).find('dutyTel1').text() + \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t+  \"<td>\"+$(this).find('dutyAddr').text() + \"</td>\";\r\n");
      out.write("\t\t\t\t\ttag += \"</tr>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\ttag += \"<table>\";\r\n");
      out.write("\t\t\t\t$('#public-data').html(tag);\r\n");
      out.write("\t\t\t\t$(\"#mypar\").modal();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(req, status){\r\n");
      out.write("\t\t\t\talert(status+\": \"+req.status);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCsrerDHJrp9Wu09Ij7MUELxCTPiYfxfBI\"></script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
